// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPermission.Data;

#nullable disable

namespace PersonalPermission.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250424101403_updateTableClassUser")]
    partial class updateTableClassUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalPermission.Core.Entities.PermissionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GainedAdministrativePermission")
                        .HasColumnType("int");

                    b.Property<int>("GainedYearlyPermission")
                        .HasColumnType("int");

                    b.Property<int>("RemainAdministrativePermission")
                        .HasColumnType("int");

                    b.Property<int>("RemainYearlyPermission")
                        .HasColumnType("int");

                    b.Property<int>("UsedAdministrativePermission")
                        .HasColumnType("int");

                    b.Property<int>("UsedYearlyPermission")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PermissionStates");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.UsedAdministrivePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ExpirationTime")
                        .HasColumnType("int");

                    b.Property<int>("StartingTime")
                        .HasColumnType("int");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YearofBelong")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsedAdministrivePermissions");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.UsedYearlyPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YearofBelong")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsedYearlyPermissions");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistryNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ServiceTimeDay")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTimeMonth")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTimeYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartingWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 24, 13, 14, 2, 67, DateTimeKind.Local).AddTicks(8049),
                            Department = "Bilgi Teknolojileri Şube Müdürlüğü",
                            IsActive = true,
                            IsAdmin = true,
                            Name = "Velat",
                            Password = "212121",
                            RegistryNo = "SP-1578",
                            ServiceTimeDay = 0,
                            ServiceTimeMonth = 11,
                            ServiceTimeYear = 1,
                            StartingWorkDate = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Surname = "BARAN",
                            Title = "Mühendis",
                            UserGuid = new Guid("ff790f5e-b765-4517-aac1-d57ddff270b5")
                        });
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.PermissionState", b =>
                {
                    b.HasOne("PersonalPermission.Core.Entities.User", "Users")
                        .WithMany("PermissionStates")
                        .HasForeignKey("UserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.UsedAdministrivePermission", b =>
                {
                    b.HasOne("PersonalPermission.Core.Entities.User", "Users")
                        .WithMany("UsedAdministrivePermissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.UsedYearlyPermission", b =>
                {
                    b.HasOne("PersonalPermission.Core.Entities.User", "Users")
                        .WithMany("UsedYearlyPermissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PersonalPermission.Core.Entities.User", b =>
                {
                    b.Navigation("PermissionStates");

                    b.Navigation("UsedAdministrivePermissions");

                    b.Navigation("UsedYearlyPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
